# Generated by Django 4.2.14 on 2025-11-23 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotation_models', '0003_quotation_created_by'),
    ]

    def gen_code(apps, schema_editor):
        SellerQuote = apps.get_model('quotation_models', 'SellerQuote')
        for sq in SellerQuote.objects.all():
            sq.seller_code = "SQ" + uuid.uuid4().hex[:8].upper()
            sq.save(update_fields=["seller_code"])

    operations = [
        migrations.AddField(
            model_name='sellerquote',
            name='seller_code',
            field=models.CharField(default='', max_length=40, blank=True),
        ),
        migrations.RunPython(gen_code, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sellerquote',
            name='seller_code',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
