# Generated by Django 4.2.14 on 2026-01-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation_models', '0004_sellerquote_seller_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='include_gst',
            field=models.BooleanField(default=True),
        ),
    ]
