# Generated by Django 5.1.2 on 2026-01-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation_models', '0005_quotation_include_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='is_gst_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
