# Generated by Django 5.1.2 on 2026-01-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation_models', '0006_quotationitem_is_gst_applicable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='include_gst',
        ),
    ]
